const books = [
  {
      "title": "Absalom, Absalom!",
      "year": 1936,
      "language": "English",
      "imageLink": "images/absalom-absalom.jpg",
      "country": "United States",
      "link": "https://en.wikipedia.org/wiki/Absalom,_Absalom!\n",
      "pages": 313,
      "author": "William Faulkner",
      "id": 1
  },
  {
      "title": "A Doll's House",
      "year": 1879,
      "language": "Norwegian",
      "imageLink": "images/a-Dolls-house.jpg",
      "country": "Norway",
      "link": "https://en.wikipedia.org/wiki/A_Doll%27s_House\n",
      "pages": 68,
      "author": "Henrik Ibsen",
      "id": 2
  },
  {
      "title": "Anna Karenina",
      "year": 1877,
      "language": "Russian",
      "imageLink": "images/anna-karenina.jpg",
      "country": "Russia",
      "link": "https://en.wikipedia.org/wiki/Anna_Karenina\n",
      "pages": 864,
      "author": "Leo Tolstoy",
      "id": 3
  },
  {
      "title": "Berlin Alexanderplatz",
      "year": 1929,
      "language": "German",
      "imageLink": "images/berlin-alexanderplatz.jpg",
      "country": "Germany",
      "link": "https://en.wikipedia.org/wiki/Berlin_Alexanderplatz\n",
      "pages": 600,
      "author": "Alfred Döblin",
      "id": 4
  },
  {
      "title": "Buddenbrooks",
      "year": 1901,
      "language": "German",
      "imageLink": "images/buddenbrooks.jpg",
      "country": "Germany",
      "link": "https://en.wikipedia.org/wiki/Buddenbrooks\n",
      "pages": 736,
      "author": "Thomas Mann",
      "id": 5
  },
  {
      "title": "Beloved",
      "year": 1987,
      "language": "English",
      "imageLink": "images/beloved.jpg",
      "country": "United States",
      "link": "https://en.wikipedia.org/wiki/Beloved_(novel)\n",
      "pages": 321,
      "author": "Toni Morrison",
      "id": 6
  },
  {
      "title": "Bostan",
      "year": 1257,
      "language": "Persian",
      "imageLink": "images/bostan.jpg",
      "country": "Persia, Persian Empire",
      "link": "https://en.wikipedia.org/wiki/Bustan_(book)\n",
      "pages": 298,
      "author": "Saadi",
      "id": 7
  },
  {
      "title": "Blindness",
      "year": 1995,
      "language": "Portuguese",
      "imageLink": "images/blindness.jpg",
      "country": "Portugal",
      "link": "https://en.wikipedia.org/wiki/Blindness_(novel)\n",
      "pages": 352,
      "author": "José Saramago",
      "id": 8
  },
  {
      "title": "Crime and Punishment",
      "year": 1866,
      "language": "Russian",
      "imageLink": "images/crime-and-punishment.jpg",
      "country": "Russia",
      "link": "https://en.wikipedia.org/wiki/Crime_and_Punishment\n",
      "pages": 551,
      "author": "Fyodor Dostoevsky",
      "id": 9
  },
  {
      "title": "Children of Gebelawi",
      "year": 1959,
      "language": "Arabic",
      "imageLink": "images/children-of-gebelawi.jpg",
      "country": "Egypt",
      "link": "https://en.wikipedia.org/wiki/Children_of_Gebelawi\n",
      "pages": 355,
      "author": "Naguib Mahfouz",
      "id": 10
  },
  {
      "title": "Confessions of Zeno",
      "year": 1923,
      "language": "Italian",
      "imageLink": "images/confessions-of-zeno.jpg",
      "country": "Italy",
      "link": "https://en.wikipedia.org/wiki/Zeno%27s_Conscience\n",
      "pages": 412,
      "author": "Italo Svevo",
      "id": 11
  },
  {
      "title": "Don Quijote De La Mancha",
      "year": 1610,
      "language": "Spanish",
      "imageLink": "images/don-quijote-de-la-mancha.jpg",
      "country": "Spain",
      "link": "https://en.wikipedia.org/wiki/Don_Quixote\n",
      "pages": 1056,
      "author": "Miguel de Cervantes",
      "id": 12
  },
  {
      "title": "Dead Souls",
      "year": 1842,
      "language": "Russian",
      "imageLink": "images/dead-souls.jpg",
      "country": "Russia",
      "link": "https://en.wikipedia.org/wiki/Dead_Souls\n",
      "pages": 432,
      "author": "Nikolai Gogol",
      "id": 13
  },
  {
      "title": "Diary of a Madman",
      "year": 1918,
      "language": "Chinese",
      "imageLink": "images/diary-of-a-madman.jpg",
      "country": "China",
      "link": "https://en.wikipedia.org/wiki/A_Madman%27s_Diary\n",
      "pages": 389,
      "author": "Lu Xun",
      "id": 14
  },
  {
      "title": "Essays",
      "year": 1595,
      "language": "French",
      "imageLink": "images/essais.jpg",
      "country": "France",
      "link": "https://en.wikipedia.org/wiki/Essays_(Montaigne)\n",
      "pages": 404,
      "author": "Michel de Montaigne",
      "id": 15
  },
  {
      "title": "Fairy tales",
      "year": 1836,
      "language": "Danish",
      "imageLink": "images/fairy-tales.jpg",
      "country": "Denmark",
      "link": "https://en.wikipedia.org/wiki/Fairy_Tales_Told_for_Children._First_Collection.\n",
      "pages": 784,
      "author": "Hans Christian Andersen",
      "id": 16
  },
  {
      "title": "Ficciones",
      "year": 1965,
      "language": "Spanish",
      "imageLink": "images/ficciones.jpg",
      "country": "Argentina",
      "link": "https://en.wikipedia.org/wiki/Ficciones\n",
      "pages": 224,
      "author": "Jorge Luis Borges",
      "id": 17
  },
  {
      "title": "Faust",
      "year": 1832,
      "language": "German",
      "imageLink": "images/faust.jpg",
      "country": "Saxe-Weimar",
      "link": "https://en.wikipedia.org/wiki/Goethe%27s_Faust\n",
      "pages": 158,
      "author": "Johann Wolfgang von Goethe",
      "id": 18
  },
  {
      "title": "Great Expectations",
      "year": 1861,
      "language": "English",
      "imageLink": "images/great-expectations.jpg",
      "country": "United Kingdom",
      "link": "https://en.wikipedia.org/wiki/Great_Expectations\n",
      "pages": 194,
      "author": "Charles Dickens",
      "id": 19
  },
  {
      "title": "Gypsy Ballads",
      "year": 1928,
      "language": "Spanish",
      "imageLink": "images/gypsy-ballads.jpg",
      "country": "Spain",
      "link": "https://en.wikipedia.org/wiki/Gypsy_Ballads\n",
      "pages": 218,
      "author": "Federico García Lorca",
      "id": 20
  },
  {
      "title": "Gargantua and Pantagruel",
      "year": 1533,
      "language": "French",
      "imageLink": "images/gargantua-and-pantagruel.jpg",
      "country": "France",
      "link": "https://en.wikipedia.org/wiki/Gargantua_and_Pantagruel\n",
      "pages": 623,
      "author": "François Rabelais",
      "id": 21
  },
  {
      "title": "Gulliver's Travels",
      "year": 1726,
      "language": "English",
      "imageLink": "images/gullivers-travels.jpg",
      "country": "Ireland",
      "link": "https://en.wikipedia.org/wiki/Gulliver%27s_Travels\n",
      "pages": 178,
      "author": "Jonathan Swift",
      "id": 22
  },
  {
      "title": "Hunger",
      "year": 1890,
      "language": "Norwegian",
      "imageLink": "images/hunger.jpg",
      "country": "Norway",
      "link": "https://en.wikipedia.org/wiki/Hunger_(Hamsun_novel)\n",
      "pages": 176,
      "author": "Knut Hamsun",
      "id": 23
  },
  {
      "title": "History",
      "year": 1974,
      "language": "Italian",
      "imageLink": "images/history.jpg",
      "country": "Italy",
      "link": "https://en.wikipedia.org/wiki/History_(novel)\n",
      "pages": 600,
      "author": "Elsa Morante",
      "id": 24
  },
  {
      "title": "Hamlet",
      "year": 1603,
      "language": "English",
      "imageLink": "images/hamlet.jpg",
      "country": "England",
      "link": "https://en.wikipedia.org/wiki/Hamlet\n",
      "pages": 432,
      "author": "William Shakespeare",
      "id": 25
  },
  {
      "title": "Invisible Man",
      "year": 1952,
      "language": "English",
      "imageLink": "images/invisible-man.jpg",
      "country": "United States",
      "link": "https://en.wikipedia.org/wiki/Invisible_Man\n",
      "pages": 581,
      "author": "Ralph Ellison",
      "id": 26
  },
  {
      "title": "Iliad",
      "year": -735,
      "language": "Greek",
      "imageLink": "images/the-iliad-of-homer.jpg",
      "country": "Greece",
      "link": "https://en.wikipedia.org/wiki/Iliad\n",
      "pages": 608,
      "author": "Homer",
      "id": 27
  },
  {
      "title": "Independent People",
      "year": 1934,
      "language": "Icelandic",
      "imageLink": "images/independent-people.jpg",
      "country": "Iceland",
      "link": "https://en.wikipedia.org/wiki/Independent_People\n",
      "pages": 470,
      "author": "Halldór Laxness",
      "id": 28
  },
  {
      "title": "In Search of Lost Time",
      "year": 1920,
      "language": "French",
      "imageLink": "images/a-la-recherche-du-temps-perdu.jpg",
      "country": "France",
      "link": "https://en.wikipedia.org/wiki/In_Search_of_Lost_Time\n",
      "pages": 2408,
      "author": "Marcel Proust",
      "id": 29
  },
  {
      "title": "Journey to the End of the Night",
      "year": 1932,
      "language": "French",
      "imageLink": "images/voyage-au-bout-de-la-nuit.jpg",
      "country": "France",
      "link": "https://en.wikipedia.org/wiki/Journey_to_the_End_of_the_Night\n",
      "pages": 505,
      "author": "Louis-Ferdinand Céline",
      "id": 30
  },
  {
      "title": "Jacques the Fatalist",
      "year": 1796,
      "language": "French",
      "imageLink": "images/jacques-the-fatalist.jpg",
      "country": "France",
      "link": "https://en.wikipedia.org/wiki/Jacques_the_Fatalist\n",
      "pages": 596,
      "author": "Denis Diderot",
      "id": 31
  },
  {
      "title": "King Lear",
      "year": 1608,
      "language": "English",
      "imageLink": "images/king-lear.jpg",
      "country": "England",
      "link": "https://en.wikipedia.org/wiki/King_Lear\n",
      "pages": 384,
      "author": "William Shakespeare",
      "id": 32
  },
  {
      "title": "Le Père Goriot",
      "year": 1835,
      "language": "French",
      "imageLink": "images/le-pere-goriot.jpg",
      "country": "France",
      "link": "https://en.wikipedia.org/wiki/Le_P%C3%A8re_Goriot\n",
      "pages": 443,
      "author": "Honoré de Balzac",
      "id": 33
  },
  {
      "title": "Love in the Time of Cholera",
      "year": 1985,
      "language": "Spanish",
      "imageLink": "images/love-in-the-time-of-cholera.jpg",
      "country": "Colombia",
      "link": "https://en.wikipedia.org/wiki/Love_in_the_Time_of_Cholera\n",
      "pages": 368,
      "author": "Gabriel García Márquez",
      "id": 34
  },
  {
      "title": "Lolita",
      "year": 1955,
      "language": "English",
      "imageLink": "images/lolita.jpg",
      "country": "Russia/United States",
      "link": "https://en.wikipedia.org/wiki/Lolita\n",
      "pages": 317,
      "author": "Vladimir Nabokov",
      "id": 35
  },
  {
      "title": "Leaves of Grass",
      "year": 1855,
      "language": "English",
      "imageLink": "images/leaves-of-grass.jpg",
      "country": "United States",
      "link": "https://en.wikipedia.org/wiki/Leaves_of_Grass\n",
      "pages": 152,
      "author": "Walt Whitman",
      "id": 36
  },
  {
      "title": "Molloy, Malone Dies, The Unnamable, the trilogy",
      "year": 1952,
      "language": "French, English",
      "imageLink": "images/molloy-malone-dies-the-unnamable.jpg",
      "country": "Republic of Ireland",
      "link": "https://en.wikipedia.org/wiki/Molloy_(novel)\n",
      "pages": 256,
      "author": "Samuel Beckett",
      "id": 37
  },
  {
      "title": "Middlemarch",
      "year": 1871,
      "language": "English",
      "imageLink": "images/middlemarch.jpg",
      "country": "United Kingdom",
      "link": "https://en.wikipedia.org/wiki/Middlemarch\n",
      "pages": 800,
      "author": "George Eliot",
      "id": 38
  },
  {
      "title": "Medea",
      "year": -431,
      "language": "Greek",
      "imageLink": "images/medea.jpg",
      "country": "Greece",
      "link": "https://en.wikipedia.org/wiki/Medea_(play)\n",
      "pages": 104,
      "author": "Euripides",
      "id": 39
  },
  {
      "title": "Madame Bovary",
      "year": 1857,
      "language": "French",
      "imageLink": "images/madame-bovary.jpg",
      "country": "France",
      "link": "https://en.wikipedia.org/wiki/Madame_Bovary\n",
      "pages": 528,
      "author": "Gustave Flaubert",
      "id": 40
  },
  {
      "title": "Moby Dick",
      "year": 1851,
      "language": "English",
      "imageLink": "images/moby-dick.jpg",
      "country": "United States",
      "link": "https://en.wikipedia.org/wiki/Moby-Dick\n",
      "pages": 378,
      "author": "Herman Melville",
      "id": 41
  },
  {
      "title": "Metamorphoses",
      "year": 100,
      "language": "Classical Latin",
      "imageLink": "images/the-metamorphoses-of-ovid.jpg",
      "country": "Roman Empire",
      "link": "https://en.wikipedia.org/wiki/Metamorphoses\n",
      "pages": 576,
      "author": "Ovid",
      "id": 42
  },
  {
      "title": "Midnight's Children",
      "year": 1981,
      "language": "English",
      "imageLink": "images/midnights-children.jpg",
      "country": "United Kingdom, India",
      "link": "https://en.wikipedia.org/wiki/Midnight%27s_Children\n",
      "pages": 536,
      "author": "Salman Rushdie",
      "id": 43
  },
  {
      "title": "Mahabharata",
      "year": -700,
      "language": "Sanskrit",
      "imageLink": "images/the-mahab-harata.jpg",
      "country": "India",
      "link": "https://en.wikipedia.org/wiki/Mahabharata\n",
      "pages": 276,
      "author": "Vyasa",
      "id": 44
  },
  {
      "title": "Mrs Dalloway",
      "year": 1925,
      "language": "English",
      "imageLink": "images/mrs-dalloway.jpg",
      "country": "United Kingdom",
      "link": "https://en.wikipedia.org/wiki/Mrs_Dalloway\n",
      "pages": 216,
      "author": "Virginia Woolf",
      "id": 45
  },
  {
      "title": "Memoirs of Hadrian",
      "year": 1951,
      "language": "French",
      "imageLink": "images/memoirs-of-hadrian.jpg",
      "country": "France/Belgium",
      "link": "https://en.wikipedia.org/wiki/Memoirs_of_Hadrian\n",
      "pages": 408,
      "author": "Marguerite Yourcenar",
      "id": 46
  },
  {
      "title": "Njál's Saga",
      "year": 1350,
      "language": "Old Norse",
      "imageLink": "images/njals-saga.jpg",
      "country": "Iceland",
      "link": "https://en.wikipedia.org/wiki/Nj%C3%A1ls_saga\n",
      "pages": 384,
      "author": "Unknown",
      "id": 47
  },
  {
      "title": "Nostromo",
      "year": 1904,
      "language": "English",
      "imageLink": "images/nostromo.jpg",
      "country": "United Kingdom",
      "link": "https://en.wikipedia.org/wiki/Nostromo\n",
      "pages": 320,
      "author": "Joseph Conrad",
      "id": 48
  },
  {
      "title": "Nineteen Eighty-Four",
      "year": 1949,
      "language": "English",
      "imageLink": "images/nineteen-eighty-four.jpg",
      "country": "United Kingdom",
      "link": "https://en.wikipedia.org/wiki/Nineteen_Eighty-Four\n",
      "pages": 272,
      "author": "George Orwell",
      "id": 49
  },
  {
      "title": "One Thousand and One Nights",
      "year": 1200,
      "language": "Arabic",
      "imageLink": "images/one-thousand-and-one-nights.jpg",
      "country": "India/Iran/Iraq/Egypt/Tajikistan",
      "link": "https://en.wikipedia.org/wiki/One_Thousand_and_One_Nights\n",
      "pages": 288,
      "author": "Unknown",
      "id": 50
  },
  {
      "title": "One Hundred Years of Solitude",
      "year": 1967,
      "language": "Spanish",
      "imageLink": "images/one-hundred-years-of-solitude.jpg",
      "country": "Colombia",
      "link": "https://en.wikipedia.org/wiki/One_Hundred_Years_of_Solitude\n",
      "pages": 417,
      "author": "Gabriel García Márquez",
      "id": 51
  },
  {
      "title": "Odyssey",
      "year": -800,
      "language": "Greek",
      "imageLink": "images/the-odyssey-of-homer.jpg",
      "country": "Greece",
      "link": "https://en.wikipedia.org/wiki/Odyssey\n",
      "pages": 374,
      "author": "Homer",
      "id": 52
  },
  {
      "title": "Othello",
      "year": 1609,
      "language": "English",
      "imageLink": "images/othello.jpg",
      "country": "England",
      "link": "https://en.wikipedia.org/wiki/Othello\n",
      "pages": 314,
      "author": "William Shakespeare",
      "id": 53
  },
  {
      "title": "Oedipus the King",
      "year": -430,
      "language": "Greek",
      "imageLink": "images/oedipus-the-king.jpg",
      "country": "Greece",
      "link": "https://en.wikipedia.org/wiki/Oedipus_the_King\n",
      "pages": 88,
      "author": "Sophocles",
      "id": 54
  },
  {
      "title": "Pride and Prejudice",
      "year": 1813,
      "language": "English",
      "imageLink": "images/pride-and-prejudice.jpg",
      "country": "United Kingdom",
      "link": "https://en.wikipedia.org/wiki/Pride_and_Prejudice\n",
      "pages": 226,
      "author": "Jane Austen",
      "id": 55
  },
  {
      "title": "Poems",
      "year": 1952,
      "language": "German",
      "imageLink": "images/poems-paul-celan.jpg",
      "country": "Romania, France",
      "link": "\n",
      "pages": 320,
      "author": "Paul Celan",
      "id": 56
  },
  {
      "title": "Poems",
      "year": 1818,
      "language": "Italian",
      "imageLink": "images/poems-giacomo-leopardi.jpg",
      "country": "Italy",
      "link": "\n",
      "pages": 184,
      "author": "Giacomo Leopardi",
      "id": 57
  },
  {
      "title": "Pippi Longstocking",
      "year": 1945,
      "language": "Swedish",
      "imageLink": "images/pippi-longstocking.jpg",
      "country": "Sweden",
      "link": "https://en.wikipedia.org/wiki/Pippi_Longstocking\n",
      "pages": 160,
      "author": "Astrid Lindgren",
      "id": 58
  },
  {
      "title": "Pedro Páramo",
      "year": 1955,
      "language": "Spanish",
      "imageLink": "images/pedro-paramo.jpg",
      "country": "Mexico",
      "link": "https://en.wikipedia.org/wiki/Pedro_P%C3%A1ramo\n",
      "pages": 124,
      "author": "Juan Rulfo",
      "id": 59
  },
  {
      "title": "Ramayana",
      "year": -450,
      "language": "Sanskrit",
      "imageLink": "images/ramayana.jpg",
      "country": "India",
      "link": "https://en.wikipedia.org/wiki/Ramayana\n",
      "pages": 152,
      "author": "Valmiki",
      "id": 60
  },
  {
      "title": "Stories",
      "year": 1886,
      "language": "Russian",
      "imageLink": "images/stories-of-anton-chekhov.jpg",
      "country": "Russia",
      "link": "https://en.wikipedia.org/wiki/List_of_short_stories_by_Anton_Chekhov\n",
      "pages": 194,
      "author": "Anton Chekhov",
      "id": 61
  },
  {
      "title": "Sentimental Education",
      "year": 1869,
      "language": "French",
      "imageLink": "images/l-education-sentimentale.jpg",
      "country": "France",
      "link": "https://en.wikipedia.org/wiki/Sentimental_Education\n",
      "pages": 606,
      "author": "Gustave Flaubert",
      "id": 62
  },
  {
      "title": "Stories",
      "year": 1924,
      "language": "German",
      "imageLink": "images/stories-of-franz-kafka.jpg",
      "country": "Czechoslovakia",
      "link": "https://en.wikipedia.org/wiki/Franz_Kafka_bibliography#Short_stories\n",
      "pages": 488,
      "author": "Franz Kafka",
      "id": 63
  },
  {
      "title": "Sons and Lovers",
      "year": 1913,
      "language": "English",
      "imageLink": "images/sons-and-lovers.jpg",
      "country": "United Kingdom",
      "link": "https://en.wikipedia.org/wiki/Sons_and_Lovers\n",
      "pages": 432,
      "author": "D. H. Lawrence",
      "id": 64
  },
  {
      "title": "Season of Migration to the North",
      "year": 1966,
      "language": "Arabic",
      "imageLink": "images/season-of-migration-to-the-north.jpg",
      "country": "Sudan",
      "link": "https://en.wikipedia.org/wiki/Season_of_Migration_to_the_North\n",
      "pages": 139,
      "author": "Tayeb Salih",
      "id": 65
  },
  {
      "title": "Things Fall Apart",
      "year": 1958,
      "language": "English",
      "imageLink": "images/things-fall-apart.jpg",
      "country": "Nigeria",
      "link": "https://en.wikipedia.org/wiki/Things_Fall_Apart\n",
      "pages": 209,
      "author": "Chinua Achebe",
      "id": 66
  },
  {
      "title": "The Divine Comedy",
      "year": 1315,
      "language": "Italian",
      "imageLink": "images/the-divine-comedy.jpg",
      "country": "Italy",
      "link": "https://en.wikipedia.org/wiki/Divine_Comedy\n",
      "pages": 928,
      "author": "Dante Alighieri",
      "id": 67
  },
  {
      "title": "The Epic Of Gilgamesh",
      "year": -1700,
      "language": "Akkadian",
      "imageLink": "images/the-epic-of-gilgamesh.jpg",
      "country": "Sumer and Akkadian Empire",
      "link": "https://en.wikipedia.org/wiki/Epic_of_Gilgamesh\n",
      "pages": 160,
      "author": "Unknown",
      "id": 68
  },
  {
      "title": "The Book Of Job",
      "year": -600,
      "language": "Hebrew",
      "imageLink": "images/the-book-of-job.jpg",
      "country": "Achaemenid Empire",
      "link": "https://en.wikipedia.org/wiki/Book_of_Job\n",
      "pages": 176,
      "author": "Unknown",
      "id": 69
  },
  {
      "title": "The Stranger",
      "year": 1942,
      "language": "French",
      "imageLink": "images/l-etranger.jpg",
      "country": "Algeria, French Empire",
      "link": "https://en.wikipedia.org/wiki/The_Stranger_(novel)\n",
      "pages": 185,
      "author": "Albert Camus",
      "id": 70
  },
  {
      "title": "The Canterbury Tales",
      "year": 1450,
      "language": "English",
      "imageLink": "images/the-canterbury-tales.jpg",
      "country": "England",
      "link": "https://en.wikipedia.org/wiki/The_Canterbury_Tales\n",
      "pages": 544,
      "author": "Geoffrey Chaucer",
      "id": 71
  },
  {
      "title": "The Idiot",
      "year": 1869,
      "language": "Russian",
      "imageLink": "images/the-idiot.jpg",
      "country": "Russia",
      "link": "https://en.wikipedia.org/wiki/The_Idiot\n",
      "pages": 656,
      "author": "Fyodor Dostoevsky",
      "id": 72
  },
  {
      "title": "The Possessed",
      "year": 1872,
      "language": "Russian",
      "imageLink": "images/the-possessed.jpg",
      "country": "Russia",
      "link": "https://en.wikipedia.org/wiki/Demons_(Dostoyevsky_novel)\n",
      "pages": 768,
      "author": "Fyodor Dostoevsky",
      "id": 73
  },
  {
      "title": "The Brothers Karamazov",
      "year": 1880,
      "language": "Russian",
      "imageLink": "images/the-brothers-karamazov.jpg",
      "country": "Russia",
      "link": "https://en.wikipedia.org/wiki/The_Brothers_Karamazov\n",
      "pages": 824,
      "author": "Fyodor Dostoevsky",
      "id": 74
  },
  {
      "title": "The Sound and the Fury",
      "year": 1929,
      "language": "English",
      "imageLink": "images/the-sound-and-the-fury.jpg",
      "country": "United States",
      "link": "https://en.wikipedia.org/wiki/The_Sound_and_the_Fury\n",
      "pages": 326,
      "author": "William Faulkner",
      "id": 75
  },
  {
      "title": "The Tin Drum",
      "year": 1959,
      "language": "German",
      "imageLink": "images/the-tin-drum.jpg",
      "country": "Germany",
      "link": "https://en.wikipedia.org/wiki/The_Tin_Drum\n",
      "pages": 600,
      "author": "Günter Grass",
      "id": 76
  },
  {
      "title": "The Devil to Pay in the Backlands",
      "year": 1956,
      "language": "Portuguese",
      "imageLink": "images/the-devil-to-pay-in-the-backlands.jpg",
      "country": "Brazil",
      "link": "https://en.wikipedia.org/wiki/The_Devil_to_Pay_in_the_Backlands\n",
      "pages": 494,
      "author": "João Guimarães Rosa",
      "id": 77
  },
  {
      "title": "The Old Man and the Sea",
      "year": 1952,
      "language": "English",
      "imageLink": "images/the-old-man-and-the-sea.jpg",
      "country": "United States",
      "link": "https://en.wikipedia.org/wiki/The_Old_Man_and_the_Sea\n",
      "pages": 128,
      "author": "Ernest Hemingway",
      "id": 78
  },
  {
      "title": "The Trial",
      "year": 1925,
      "language": "German",
      "imageLink": "images/the-trial.jpg",
      "country": "Czechoslovakia",
      "link": "https://en.wikipedia.org/wiki/The_Trial\n",
      "pages": 160,
      "author": "Franz Kafka",
      "id": 79
  },
  {
      "title": "The Castle",
      "year": 1926,
      "language": "German",
      "imageLink": "images/the-castle.jpg",
      "country": "Czechoslovakia",
      "link": "https://en.wikipedia.org/wiki/The_Castle_(novel)\n",
      "pages": 352,
      "author": "Franz Kafka",
      "id": 80
  },
  {
      "title": "The recognition of Shakuntala",
      "year": 150,
      "language": "Sanskrit",
      "imageLink": "images/the-recognition-of-shakuntala.jpg",
      "country": "India",
      "link": "https://en.wikipedia.org/wiki/Abhij%C3%B1%C4%81na%C5%9B%C4%81kuntalam\n",
      "pages": 147,
      "author": "Kālidāsa",
      "id": 81
  },
  {
      "title": "The Sound of the Mountain",
      "year": 1954,
      "language": "Japanese",
      "imageLink": "images/the-sound-of-the-mountain.jpg",
      "country": "Japan",
      "link": "https://en.wikipedia.org/wiki/The_Sound_of_the_Mountain\n",
      "pages": 288,
      "author": "Yasunari Kawabata",
      "id": 82
  },
  {
      "title": "The Golden Notebook",
      "year": 1962,
      "language": "English",
      "imageLink": "images/the-golden-notebook.jpg",
      "country": "United Kingdom",
      "link": "https://en.wikipedia.org/wiki/The_Golden_Notebook\n",
      "pages": 688,
      "author": "Doris Lessing",
      "id": 83
  },
  {
      "title": "The Magic Mountain",
      "year": 1924,
      "language": "German",
      "imageLink": "images/the-magic-mountain.jpg",
      "country": "Germany",
      "link": "https://en.wikipedia.org/wiki/The_Magic_Mountain\n",
      "pages": 720,
      "author": "Thomas Mann",
      "id": 84
  },
  {
      "title": "The Tale of Genji",
      "year": 1006,
      "language": "Japanese",
      "imageLink": "images/the-tale-of-genji.jpg",
      "country": "Japan",
      "link": "https://en.wikipedia.org/wiki/The_Tale_of_Genji\n",
      "pages": 1360,
      "author": "Murasaki Shikibu",
      "id": 85
  },
  {
      "title": "The Man Without Qualities",
      "year": 1931,
      "language": "German",
      "imageLink": "images/the-man-without-qualities.jpg",
      "country": "Austria",
      "link": "https://en.wikipedia.org/wiki/The_Man_Without_Qualities\n",
      "pages": 365,
      "author": "Robert Musil",
      "id": 86
  },
  {
      "title": "The Book of Disquiet",
      "year": 1928,
      "language": "Portuguese",
      "imageLink": "images/the-book-of-disquiet.jpg",
      "country": "Portugal",
      "link": "https://en.wikipedia.org/wiki/The_Book_of_Disquiet\n",
      "pages": 272,
      "author": "Fernando Pessoa",
      "id": 87
  },
  {
      "title": "Tales",
      "year": 1950,
      "language": "English",
      "imageLink": "images/tales-and-poems-of-edgar-allan-poe.jpg",
      "country": "United States",
      "link": "https://en.wikipedia.org/wiki/Edgar_Allan_Poe_bibliography#Tales\n",
      "pages": 842,
      "author": "Edgar Allan Poe",
      "id": 88
  },
  {
      "title": "The Masnavi",
      "year": 1236,
      "language": "Persian",
      "imageLink": "images/the-masnavi.jpg",
      "country": "Sultanate of Rum",
      "link": "https://en.wikipedia.org/wiki/Masnavi\n",
      "pages": 438,
      "author": "Rumi",
      "id": 89
  },
  {
      "title": "The Red and the Black",
      "year": 1830,
      "language": "French",
      "imageLink": "images/le-rouge-et-le-noir.jpg",
      "country": "France",
      "link": "https://en.wikipedia.org/wiki/The_Red_and_the_Black\n",
      "pages": 576,
      "author": "Stendhal",
      "id": 90
  },
  {
      "title": "The Life And Opinions of Tristram Shandy",
      "year": 1760,
      "language": "English",
      "imageLink": "images/the-life-and-opinions-of-tristram-shandy.jpg",
      "country": "England",
      "link": "https://en.wikipedia.org/wiki/The_Life_and_Opinions_of_Tristram_Shandy,_Gentleman\n",
      "pages": 640,
      "author": "Laurence Sterne",
      "id": 91
  },
  {
      "title": "The Death of Ivan Ilyich",
      "year": 1886,
      "language": "Russian",
      "imageLink": "images/the-death-of-ivan-ilyich.jpg",
      "country": "Russia",
      "link": "https://en.wikipedia.org/wiki/The_Death_of_Ivan_Ilyich\n",
      "pages": 92,
      "author": "Leo Tolstoy",
      "id": 92
  },
  {
      "title": "The Adventures of Huckleberry Finn",
      "year": 1884,
      "language": "English",
      "imageLink": "images/the-adventures-of-huckleberry-finn.jpg",
      "country": "United States",
      "link": "https://en.wikipedia.org/wiki/Adventures_of_Huckleberry_Finn\n",
      "pages": 224,
      "author": "Mark Twain",
      "id": 93
  },
  {
      "title": "The Aeneid",
      "year": -23,
      "language": "Classical Latin",
      "imageLink": "images/the-aeneid.jpg",
      "country": "Roman Empire",
      "link": "https://en.wikipedia.org/wiki/Aeneid\n",
      "pages": 442,
      "author": "Virgil",
      "id": 94
  },
  {
      "title": "To the Lighthouse",
      "year": 1927,
      "language": "English",
      "imageLink": "images/to-the-lighthouse.jpg",
      "country": "United Kingdom",
      "link": "https://en.wikipedia.org/wiki/To_the_Lighthouse\n",
      "pages": 209,
      "author": "Virginia Woolf",
      "id": 95
  },
  {
      "title": "Ulysses",
      "year": 1922,
      "language": "English",
      "imageLink": "images/ulysses.jpg",
      "country": "Irish Free State",
      "link": "https://en.wikipedia.org/wiki/Ulysses_(novel)\n",
      "pages": 228,
      "author": "James Joyce",
      "id": 96
  },
  {
      "title": "Wuthering Heights",
      "year": 1847,
      "language": "English",
      "imageLink": "images/wuthering-heights.jpg",
      "country": "United Kingdom",
      "link": "https://en.wikipedia.org/wiki/Wuthering_Heights\n",
      "pages": 342,
      "author": "Emily Brontë",
      "id": 97
  },
  {
      "title": "War and Peace",
      "year": 1867,
      "language": "Russian",
      "imageLink": "images/war-and-peace.jpg",
      "country": "Russia",
      "link": "https://en.wikipedia.org/wiki/War_and_Peace\n",
      "pages": 1296,
      "author": "Leo Tolstoy",
      "id": 98
  },
  {
      "title": "Zorba the Greek",
      "year": 1946,
      "language": "Greek",
      "imageLink": "images/zorba-the-greek.jpg",
      "country": "Greece",
      "link": "https://en.wikipedia.org/wiki/Zorba_the_Greek\n",
      "pages": 368,
      "author": "Nikos Kazantzakis",
      "id": 99
  }
]